.localvar 2 arguments

:[0]
pushi.e 0
pop.v.i self.drawx
pushi.e 0
pop.v.i self.drawx_temp
pushi.e 0
pop.v.i self.drawy
pushi.e 0
pop.v.b self.show_laser_outline
pushi.e 0
pop.v.i self.siner
pushi.e 0
pop.v.i self.go_away_y
pushi.e 0
pop.v.b self.cityscape_reveal
pushi.e -1
pop.v.i self.reveal_pos
pushi.e 0
pop.v.b self.auto_scroll
pushi.e 0
pop.v.b self.auto_scroll_y
pushi.e 0
pop.v.i self.auto_scroll_y_timer
pushi.e 0
pop.v.i self.scroll
pushi.e 0
pop.v.i self.y_offset
pushi.e 0
pop.v.i self.x_offset
pushi.e 0
pop.v.b self.show_laser_hand
pushi.e 0
pop.v.b self.hand_reveal
pushi.e -1
pop.v.i self.hand_reveal_pos
pushi.e -1
pop.v.i self.hand_reveal_pos_start
pushi.e 0
pop.v.i self.hand_index
pushi.e 0
pop.v.i self.hand_rotation
pushi.e 0
pop.v.b self.hand_rotate
pushi.e 1
pop.v.i self.hand_alpha
pushi.e 0
pop.v.b self.show_laser_knife
pushi.e 0
pop.v.b self.hand_switch
pushi.e 0
pop.v.b self.show_laser_beam
pushi.e 0
pop.v.i self.beam_offset
pushi.e 0
pop.v.b self.fade_away
pushi.e 1
pop.v.i self.main_alpha
pushi.e 0
pop.v.b self.show_lightners
pushi.e 0
pop.v.b self.show_mini_fountains
pushi.e 0
pop.v.b self.merge_lightners
pushi.e 30
pop.v.i self.merge_timer
pushi.e 0
pop.v.i self.mini_alpha
pushi.e 0
pop.v.b self.mini_cityscape
pushi.e 0
pop.v.b self.make_new
pushi.e 160
pop.v.i self.screen_offset
pushi.e 1
pop.v.i self.screen_alpha
pushi.e 0
pop.v.b self.fade_screens
pushi.e -4
pop.v.i self.kris_screen
pushi.e -4
pop.v.i self.sus_screen
pushi.e -4
pop.v.i self.no_screen
pushi.e 0
pop.v.b self.tender_goodbye
pushi.e 0
pop.v.b self.tender_reveal
pushi.e -1
pop.v.i self.tender_reveal_pos
pushi.e 0
pop.v.b self.tender_cancel
pushi.e 0
pop.v.b self.tender_cancel_reveal
pushi.e -1
pop.v.i self.tender_cancel_pos
pushi.e 0
pop.v.b self.tender_fly
pushi.e 0
pop.v.i self.sinery
pushi.e 1
pop.v.i self.tender_alpha
pushi.e 30
pop.v.i self.tender_timer
pushi.e 0
pop.v.i self.tender_fade
pushi.e -1
pop.v.i self.hand_right_xpos
pushi.e 0
pop.v.b self.hand_both_reveal
pushi.e 0
pop.v.b self.hand_both_reveal_finish
pushi.e 0
pop.v.b self.hand_init
pushi.e 0
pop.v.b self.knife_reveal
call.i gml_Script_cameray(argc=0)
pushi.e 313
conv.i.v
call.i sprite_get_height(argc=1)
pushi.e 2
mul.i.v
sub.v.v
pop.v.v self.knife_ypos
pushi.e -2
pop.v.i self.knife_alpha
pushi.e 0
pop.v.b self.knife_hover
pushi.e 0
pop.v.i self.knife_siner
pushi.e 0
pop.v.b self.knife_stab
pushi.e 0
pop.v.i self.stab_timer
pushi.e 0
pop.v.b self.hand_retreat
pushi.e 0
pop.v.i self.retreat_timer
pushi.e 0
pop.v.b self.show_hands
push.s "spr_cutscene_27_tender_goodbye"@12028
conv.s.v
call.i gml_Script_scr_84_get_sprite(argc=1)
pop.v.v self.byebye_sprite

:[end]