.localvar 2 arguments

:[0]
pushi.e 0
pop.v.i self.HeroID
pushi.e 0
pop.v.i self.xx
pushi.e 0
pop.v.i self.yy
pushi.e 1
pop.v.i self.forceact
pushi.e 0
pop.v.i self.gooffscreen
pushi.e 0
pop.v.i self.userealsprite
pushi.e 1
pop.v.i self.introanim
pushi.e 0
pop.v.i self.endtargetx
push.d 0.25
pop.v.d self.image_speed
pushi.e 2
pop.v.i self.image_xscale
pushi.e 2
pop.v.i self.image_yscale
pushi.e 1859
pop.v.i self.mask_index
pushi.e 0
pop.v.i self.siner
pushi.e 0
pop.v.i self.smoketimer
pushi.e 0
pop.v.i self.con
pushi.e 0
pop.v.i self.action
pushi.e 81
pop.v.i self.mykey
pushi.e 0
pop.v.i self.damaged
pushi.e 0
pop.v.i self.mykeybuffer
pushi.e 0
pop.v.i self.nitro
pushi.e 0
pop.v.i self.barrier
pushi.e 0
pop.v.i self.disabled
pushi.e 0
pop.v.i self.disabledtimer
pushi.e 0
pop.v.i self.disabledtype
pushi.e 0
pop.v.i self.flametimer
pushi.e 0
pop.v.i self.flameindex
pushi.e 0
pop.v.i self.flameindextimer
pushi.e 0
pop.v.i self.fsiner
pushi.e 0
pop.v.i self.actoncondelay
pushi.e 0
pop.v.i self.dontshowherosprite
pushi.e 0
pop.v.i self.draw_button_press
pushi.e 0
pop.v.i self.draw_button_press_timer

:[end]