.localvar 2 arguments

:[0]
pushi.e 1
pop.v.i self.type
pushi.e 99
pop.v.i self.btimer
pushi.e 0
pop.v.i self.ctimer
pushi.e 0
pop.v.i self.dtimer
pushi.e 12
pop.v.i self.timermax
pushi.e 9
pop.v.i self.threshold
pushi.e 0
pop.v.i self.wineadded
pushi.e 4
pop.v.i self.wineadd
pushi.e 10
pop.v.i self.turnamount
pushi.e 15
pop.v.i self.turnperiod
pushi.e 0
pop.v.i self.dropletcount
pushi.e 0
pop.v.i self.winedebug
push.i 171058
setowner.e
pushi.e 0
conv.i.v
pushi.e -1
pushi.e 2
pop.v.v [array]self.stomplocation
pushi.e -1
pop.v.i self.damage
pushi.e -1
pop.v.i self.grazepoints
pushi.e -1
pop.v.i self.timepoints
pushi.e -1
pop.v.i self.inv
pushi.e -1
pop.v.i self.grazed
pushi.e -1
pop.v.i self.grazetimer
push.s "none"@562
pop.v.s self.element
pushi.e -1
pop.v.i self.target
pushi.e 1
pop.v.i self.side
pushi.e 1
pop.v.i self.difficulty
pushi.e 0
pop.v.i self.made
pushi.e 0
pop.v.i self.special
pushi.e 0
pop.v.i self.chooselocation
pushi.e 2
conv.i.v
call.i irandom(argc=1)
pop.v.v self.a
pushi.e 0
pop.v.i self.init
pushi.e 0
pop.v.i self.sameattack
pushi.e 0
pop.v.i self.sameattacker
pushi.e 999
pop.v.i self.miny
pushi.e 999
pop.v.i self.maxy
pushi.e 999
pop.v.i self.maxx
pushi.e 999
pop.v.i self.miny
pushi.e 0
pop.v.i self.creator
pushi.e 574
pop.v.i self.queen
pushi.e 0
pop.v.i self.lastType
pushi.e 0
pop.v.i self.buffertimer
pushi.e 0
pop.v.i self.bufferattack
pushi.e 0
pop.v.i self.extra
pushi.e -1
pop.v.i self.lastside
pushi.e 0
pop.v.i self.siner
pushi.e 0
pop.v.i self.loopsfx

:[end]