.localvar 2 arguments

:[0]
pushi.e 0
pop.v.i self.char
pushi.e 0
pop.v.i self.myself
pushi.e 0
pop.v.i self.points
pushi.e 0
pop.v.i self.becomeflash
pushi.e 0
pop.v.i self.state
pushi.e 0
pop.v.i self.flash
pushi.e 0
pop.v.i self.siner
pushi.e 0
pop.v.i self.fsiner
pushi.e 0
pop.v.i self.attacktimer
pushi.e 0
pop.v.i self.attacked
pushi.e 1
pop.v.i self.combatdarken
pushi.e 0
pop.v.i self.darkentimer
pushi.e 0
pop.v.i self.darkify
pushi.e 2
pop.v.i self.image_xscale
pushi.e 2
pop.v.i self.image_yscale
pushi.e 37
pop.v.i self.myheight
pushi.e 34
pop.v.i self.mywidth
pushi.e 0
pop.v.i self.index
pushi.e 0
pop.v.i self.specdraw
pushi.e 0
pop.v.i self.is_auto_susie
pushi.e 4202
pop.v.i self.normalsprite
pushi.e 3828
pop.v.i self.idlesprite
pushi.e 3821
pop.v.i self.actreadysprite
pushi.e 3820
pop.v.i self.actsprite
pushi.e 3826
pop.v.i self.hurtsprite
pushi.e 3819
pop.v.i self.defendsprite
pushi.e 3819
pop.v.i self.attackreadysprite
pushi.e 3824
pop.v.i self.attacksprite
pushi.e 3823
pop.v.i self.itemsprite
pushi.e 3822
pop.v.i self.itemreadysprite
pushi.e 3868
pop.v.i self.spellreadysprite
pushi.e 3867
pop.v.i self.spellsprite
pushi.e 3818
pop.v.i self.defeatsprite
pushi.e 3817
pop.v.i self.victorysprite
pushi.e 0
pop.v.i self.victoryanim
pushi.e 7
pop.v.i self.actframes
pushi.e 9
pop.v.i self.victoryframes
pushi.e 1
pop.v.i self.defendframes
pushi.e 3
pop.v.i self.itemframes
pushi.e 3
pop.v.i self.attackframes
push.d 0.5
pop.v.d self.attackspeed
pushi.e 7
pop.v.i self.actframes
pushi.e 10
pop.v.i self.actreturnframes
pushi.e 10
pop.v.i self.spellframes
pushi.e 0
pop.v.i self.hurt
pushi.e 0
pop.v.i self.hurttimer
pushi.e 0
pop.v.i self.hurtindex
pushi.e 0
pop.v.i self.acttimer
pushi.e 0
pop.v.i self.defendtimer
pushi.e 0
pop.v.i self.itemed
pushi.e 0
pop.v.i self.tu
push.v self.object_index
pushi.e 1534
cmp.i.v EQ
bf [2]

:[1]
pushi.e 4202
pop.v.i self.normalsprite
pushi.e 3828
pop.v.i self.idlesprite
pushi.e 3829
pop.v.i self.defendsprite
pushi.e 3826
pop.v.i self.hurtsprite
pushi.e 3819
pop.v.i self.attackreadysprite
pushi.e 3824
pop.v.i self.attacksprite
pushi.e 3823
pop.v.i self.itemsprite
pushi.e 3821
pop.v.i self.actreadysprite
pushi.e 3820
pop.v.i self.actsprite
pushi.e 3822
pop.v.i self.itemreadysprite
pushi.e 3821
pop.v.i self.spellreadysprite
pushi.e 3820
pop.v.i self.spellsprite
pushi.e 3818
pop.v.i self.defeatsprite
pushi.e 3817
pop.v.i self.victorysprite
pushi.e 7
pop.v.i self.actframes
pushi.e 10
pop.v.i self.actreturnframes
pushi.e 6
pop.v.i self.attackframes
pushi.e 6
pop.v.i self.itemframes
pushi.e 5
pop.v.i self.defendframes
pushi.e 10
pop.v.i self.spellframes
push.d 0.5
pop.v.d self.attackspeed
push.v self.victorysprite
call.i sprite_get_number(argc=1)
pop.v.v self.victoryframes
pushi.e 68
pop.v.i self.mywidth
pushi.e 74
pop.v.i self.myheight

:[2]
push.v self.object_index
pushi.e 1535
cmp.i.v EQ
bf [6]

:[3]
pushi.e 5
pop.v.i self.attackframes
pushi.e 5
pop.v.i self.itemframes
pushi.e 5
pop.v.i self.defendframes
pushi.e 7
pop.v.i self.actframes
pushi.e 10
pop.v.i self.actreturnframes
pushi.e 8
pop.v.i self.spellframes
push.d 0.5
pop.v.d self.attackspeed
pushi.e 3549
pop.v.i self.normalsprite
pushi.e 3833
pop.v.i self.idlesprite
pushi.e 3840
pop.v.i self.defendsprite
pushi.e 3839
pop.v.i self.hurtsprite
pushi.e 3835
pop.v.i self.actreadysprite
pushi.e 3836
pop.v.i self.actsprite
pushi.e 3847
pop.v.i self.attackreadysprite
pushi.e 3844
pop.v.i self.attacksprite
pushi.e -5
pushi.e 2
push.v [array]self.charweapon
pushi.e 0
cmp.i.v EQ
bf [5]

:[4]
pushi.e 3843
pop.v.i self.idlesprite
pushi.e 3849
pop.v.i self.attackreadysprite
pushi.e 3846
pop.v.i self.attacksprite

:[5]
pushi.e 3838
pop.v.i self.itemsprite
pushi.e 3837
pop.v.i self.itemreadysprite
pushi.e 3832
pop.v.i self.spellreadysprite
pushi.e 3834
pop.v.i self.spellsprite
pushi.e 3842
pop.v.i self.defeatsprite
pushi.e 3831
pop.v.i self.victorysprite
push.v self.victorysprite
call.i sprite_get_number(argc=1)
pop.v.v self.victoryframes
pushi.e 70
pop.v.i self.mywidth
pushi.e 82
pop.v.i self.myheight

:[6]
push.v self.object_index
pushi.e 1536
cmp.i.v EQ
bf [end]

:[7]
pushi.e 5
pop.v.i self.attackframes
pushi.e 7
pop.v.i self.itemframes
pushi.e 6
pop.v.i self.defendframes
pushi.e 7
pop.v.i self.actframes
pushi.e 10
pop.v.i self.actreturnframes
push.d 0.5
pop.v.d self.attackspeed
pushi.e 3575
pop.v.i self.normalsprite
pushi.e 3852
pop.v.i self.idlesprite
pushi.e 3864
pop.v.i self.defendsprite
pushi.e 3865
pop.v.i self.hurtsprite
pushi.e 3860
pop.v.i self.attackreadysprite
pushi.e 3861
pop.v.i self.attacksprite
pushi.e 3862
pop.v.i self.itemsprite
pushi.e 3863
pop.v.i self.itemreadysprite
pushi.e 3868
pop.v.i self.spellreadysprite
pushi.e 3867
pop.v.i self.spellsprite
pushi.e 3857
pop.v.i self.defeatsprite
pushi.e 3858
pop.v.i self.victorysprite
pushi.e 3855
pop.v.i self.actreadysprite
pushi.e 3854
pop.v.i self.actsprite
push.v self.victorysprite
call.i sprite_get_number(argc=1)
pop.v.v self.victoryframes
pushi.e 52
pop.v.i self.mywidth
pushi.e 86
pop.v.i self.myheight

:[end]