.localvar 2 arguments

:[0]
call.i event_inherited(argc=0)
popz.v
pushi.e 1
pop.v.i self.mode
pushi.e 6
pop.v.i self.riseSpeed
pushi.e 2
pop.v.i self.riseSpeedInitial
push.d 0.25
pop.v.d self.riseSpeedBoostFriction
pushi.e 0
pop.v.i self.riseSpeedBoost
pushi.e 15
pop.v.i self.riseSpeedBoostMax
pushi.e 12
pop.v.i self.riseSpeedReverse
pushi.e 6
pop.v.i self.spinSpeed
push.v self.ystart
pushi.e 100
sub.i.v
pop.v.v self.endY
pushi.e 20
pop.v.i self.jumpOutDuration
pushi.e 20
pop.v.i self.jumpInDuration
pushi.e -1
pop.v.i self.holdHeight
pushi.e 0
pop.v.i self.holdDistance
pushi.e 1
pop.v.b self.camFollow
pushi.e 0
pop.v.i self.camFollowAfter
pushbltn.v builtin.undefined
pop.v.v self.specialEnding
pushbltn.v builtin.undefined
pop.v.v self.startOffset
push.i 174199
setowner.e
pushbltn.v builtin.undefined
pushbltn.v builtin.undefined
call.i @@NewGMLArray@@(argc=2)
pushi.e -1
pushi.e 0
pop.v.v [array]self.endPos
pushbltn.v builtin.undefined
pushbltn.v builtin.undefined
call.i @@NewGMLArray@@(argc=2)
pushi.e -1
pushi.e 1
pop.v.v [array]self.endPos
pushbltn.v builtin.undefined
pushbltn.v builtin.undefined
call.i @@NewGMLArray@@(argc=2)
pushi.e -1
pushi.e 2
pop.v.v [array]self.endPos
push.i 174200
setowner.e
pushbltn.v builtin.undefined
pushbltn.v builtin.undefined
call.i @@NewGMLArray@@(argc=2)
pushi.e -1
pushi.e 0
pop.v.v [array]self.startPos
pushbltn.v builtin.undefined
pushbltn.v builtin.undefined
call.i @@NewGMLArray@@(argc=2)
pushi.e -1
pushi.e 1
pop.v.v [array]self.startPos
pushbltn.v builtin.undefined
pushbltn.v builtin.undefined
call.i @@NewGMLArray@@(argc=2)
pushi.e -1
pushi.e 2
pop.v.v [array]self.startPos
pushi.e 1
pop.v.b self.centerX
pushi.e 0
pop.v.b self.centerY
pushi.e 0
pop.v.b self.returnOnFinish
pushi.e 0
pop.v.b self.fadeOutOthers
pushi.e 0
pop.v.b self.bulletsApplyToAll
pushi.e 0
pop.v.b self.scoreboardExists
pushi.e 10
pop.v.i self.scoreboardGoal
pushi.e 0
pop.v.b self.tutorialRide
pushi.e 1
pop.v.b self.regenerateBullets
pushi.e 350
pop.v.i self.camTargetHeightNormal
pushi.e 240
pop.v.i self.camTargetHeightReverse
pushi.e -1
pop.v.i self.uniqueBulletPattern
pushbltn.v builtin.undefined
pop.v.v self.uniqueRideExperience
pushi.e -4
pop.v.i self.jumpToRide

:[end]